import type { LucideIcon } from "lucide-react";
import {
	Anchor,
	ArrowDownIcon,
	ArrowRightLeft,
	ArrowUpIcon,
	BanknoteArrowUp,
	BarChart3,
	BellRing,
	BookText,
	Bot,
	Building2,
	CircleEllipsis,
	CircleUser,
	Factory,
	Home,
	KeyRound,
	LayoutDashboard,
	LineChart,
	Logs,
	MessageSquare,
	MessageSquareShare,
	PiggyBank,
	TrendingUpDown,
	User,
} from "lucide-react";
import { SidepanelTabs } from "@/types/sidepanel-type";

export const TOP_TRADERS_PROPS = {
	topgainers: { initialTab: "gainers" as const },
	toploosers: { initialTab: "losers" as const },
	toptransactions: { initialTab: "transactions" as const },
	topturnovers: { initialTab: "turnovers" as const },
	topvolume: { initialTab: "traded" as const },
} as const;

export interface TabItem {
	icon: LucideIcon;
	name: string;
	alias: string;
	description: string;
	color?: string;
	canPin?: boolean;
	route?: string;
	params?: Record<string, unknown>;
}

export const dashboardItems: TabItem[] = [
	{
		icon: CircleUser,
		name: "Accounts",
		alias: "account",
		description: "Manage accounts",
		color: "bg-indigo-500/10 dark:bg-indigo-500/20",
		canPin: true,
		route: "/account",
	},
	{
		icon: User,
		name: "Profile",
		alias: "profile",
		description: "Manage profile",
		color: "bg-purple-500/10 dark:bg-purple-500/20",
		canPin: true,
		route: "/profile",
		params: { fromAuthFlow: false },
	},
	{
		icon: ArrowUpIcon,
		name: "Top Gainers",
		alias: "topgainers",
		description: "Top Gainers list",
		color: "bg-green-500/10 dark:bg-green-500/20",
		canPin: true,
		route: "/toptraders",
		params: { initialTab: "gainers" },
	},
	{
		icon: ArrowDownIcon,
		name: "Top Losers",
		alias: "toploosers",
		description: "Top Losers list",
		color: "bg-rose-500/10 dark:bg-rose-500/20",
		canPin: true,
		route: "/toptraders",
		params: { initialTab: "losers" },
	},
	{
		icon: TrendingUpDown,
		name: "Sentiment",
		alias: "sentiment",
		description: "Market Sentiment",
		color: "bg-amber-500/10 dark:bg-amber-500/20",
		canPin: true,
		route: "/sentiment",
	},
	{
		icon: CircleEllipsis,
		name: "Market Indices",
		alias: "marketindices",
		description: "Market Overview",
		color: "bg-pink-500/10 dark:bg-pink-500/20",
		canPin: true,
		route: "/market-indices",
	},
	{
		icon: Building2,
		name: "Listed Stocks",
		alias: "listedstocks",
		description: "View all stocks",
		color: "bg-orange-500/10 dark:bg-orange-500/20",
		canPin: true,
		route: "/company-list",
	},
	{
		icon: Anchor,
		name: "Market Depth",
		alias: "marketdepth",
		description: "View order depth",
		color: "bg-blue-500/10 dark:bg-blue-500/20",
		canPin: true,
		route: "/marketdepth",
	},
	{
		icon: Logs,
		name: "Highest orders",
		alias: "supplydemand",
		description: "View highest orders",
		color: "bg-fuchsia-500/10 dark:bg-fuchsia-500/20",
		canPin: true,
		route: "/supply-demand",
	},
	{
		icon: ArrowRightLeft,
		name: "Top Transactions",
		alias: "toptransactions",
		description: "Top Transactions list",
		color: "bg-lime-500/10 dark:bg-lime-500/20",
		canPin: true,
		route: "/toptraders",
		params: { initialTab: "transactions" },
	},
	{
		icon: BarChart3,
		name: "Top Turnovers",
		alias: "topturnovers",
		description: "Top Turnovers list",
		color: "bg-cyan-500/10 dark:bg-cyan-500/20",
		canPin: true,
		route: "/toptraders",
		params: { initialTab: "turnovers" },
	},
	{
		icon: LineChart,
		name: "Top Volume",
		alias: "topvolume",
		description: "Top Volume list",
		color: "bg-yellow-500/10 dark:bg-yellow-500/20",
		canPin: true,
		route: "/toptraders",
		params: { initialTab: "traded" },
	},
	{
		icon: MessageSquareShare,
		name: "Join Telegram",
		alias: "telegram",
		description: "Join Telegram group",
		color: "bg-sky-500/10 dark:bg-sky-500/20",
		canPin: false,
	},
	{
		icon: PiggyBank,
		name: "Portfolio",
		alias: "portfolio",
		description: "View portfolio",
		color: "bg-emerald-500/10 dark:bg-emerald-500/20",
		canPin: true,
		route: "/portfolio",
	},
	{
		icon: BanknoteArrowUp,
		name: "IPO	",
		alias: "ipo",
		description: "View Upcoming IPOs",
		color: "bg-blue-500/10 dark:bg-blue-500/20",
		canPin: true,
		route: "/ipo",
	},
	{
		icon: MessageSquare,
		name: "Chat",
		alias: "chat",
		description: "View chat community",
		color: "bg-red-500/10 dark:bg-red-500/20",
		canPin: true,
		route: "/community-chat",
	},
	{
		icon: Bot,
		name: "AI Chat",
		alias: "aichat",
		description: "View AI chat",
		color: "bg-violet-500/10 dark:bg-violet-500/20",
		canPin: true,
		route: "/ai-chat",
	},
	{
		icon: BellRing,
		name: "Notifications",
		alias: "notifications",
		description: "View all notifications",
		color: "bg-orange-500/10 dark:bg-orange-500/20",
		canPin: true,
		route: "/notifications",
	},
	{
		icon: KeyRound,
		name: "Keys",
		alias: "keys",
		description: "API Keys management",
		color: "bg-amber-500/10 dark:bg-amber-500/20",
		canPin: true,
		route: "/keys",
	},
	{
		icon: BookText,
		name: "Disclosures",
		alias: "disclosures",
		description: "Disclosure and reports",
		color: "bg-orange-500/10 dark:bg-orange-500/20",
		canPin: true,
		route: "/disclosures",
	},
	{
		icon: Factory,
		name: "High Caps",
		alias: "highcaps",
		description: "Top Companies by Market Cap",
		color: "bg-purple-500/10 dark:bg-purple-500/20",
		canPin: true,
		route: "/high-caps",
	},
];

export const DEFAULTTABS: TabItem[] = [
	{
		name: SidepanelTabs.HOME,
		alias: "home",
		icon: Home,
		description: "Home tab with market overview",
	},
	{
		name: SidepanelTabs.DASHBOARD,
		alias: "dashboard",
		icon: LayoutDashboard,
		description: "Overview of all widgets",
	},
];
