export const URLS = {
	review_url: "https://link.nepsechatbot.com/review",
	privacy_url: "https://link.nepsechatbot.com/privacy",
	terms_url: "https://link.nepsechatbot.com/terms",
	changelog_url: "https://link.nepsechatbot.com/changelog",
	telegram_url: "https://link.nepsechatbot.com/telegram",
	welcome_url: "https://link.nepsechatbot.com/welcome",
	uninstall_url: "https://link.nepsechatbot.com/uninstall",
	github_url: "https://link.nepsechatbot.com/github",
	chart_url: "https://nepsealpha.com/nepse-chart?symbol=",
	chat_url: "https://www.nepsechatbot.com/chat",
	community_chat_url: "https://www.nepsechatbot.com/community",
	inference_url: "https://www.nepsechatbot.com",
	cdn_url: "https://cdn.nepsechatbot.com",
};
