packages:
  - packages/*
  - apps/*

catalog:
  '@tailwindcss/postcss': ^4.1.18
  "ai": '^5.0.93'
  '@tailwindcss/vite': ^4.1.17
  '@tanstack/react-table': ^8.21.3
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  autoprefixer: ^10.4.23
  babel-plugin-react-compiler: 19.1.0-rc.3
  better-auth: ^1.3.34
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: 1.1.1
  convex: ^1.30.0
  convex-helpers: ^0.1.108
  framer-motion: ^12.23.25
  input-otp: ^1.4.2
  lucide-react: 0.562.0
  next-themes: ^0.4.6
  postcss: ^8.5.6
  postcss-rem-to-responsive-pixel: ^7.0.0
  react: ^19.2.3
  react-dom: ^19.2.3
  react-resizable-panels: ^3.0.4
  recharts: 3.4.1
  sonner: ^2.0.7
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tailwindcss-animate: ^1.0.7
  tw-animate-css: ^1.4.0
  typescript: latest
  vaul: ^1.1.2

peerDependencyRules:
  allowedVersions:
    '@ai-sdk/provider-utils>zod': '*'
    '@ai-sdk/react>zod': '*'
    '@ai-sdk/ui-utils>zod': '*'
    '@convex-dev/action-retrier>convex': '*'
    '@convex-dev/auth>@auth/core': '*'
    '@tanstack/zod-form-adapter>zod': '*'
    ai>zod: '*'
    convex-helpers>zod: '*'
    react-side-effect>react: '*'
    zod-to-json-schema>zod: '*'
