import { AI_CODES, type aiErrors } from "@nepse-dashboard/ai/types";
import { Button } from "@nepse-dashboard/ui/components/button";
import {
	AlertCircle,
	AlertTriangle,
	Clock,
	KeyRound,
	Languages,
	Lock,
} from "lucide-react";
import useScreenView from "@/hooks/usePageView";
import { useNewsState } from "../store";
import { ApiKeySettings } from "./api-key-settings";

type ErrorDisplayProps = {
	error: aiErrors | null;
	onRetry?: () => void;
	onClose?: () => void;
};

const ERROR_CONFIG: Record<
	aiErrors,
	{ title: string; icon: typeof AlertCircle; showRetry: boolean }
> = {
	[AI_CODES.MISSING_PARAMS]: {
		title: "Configuration Error",
		icon: AlertTriangle,
		showRetry: false,
	},
	[AI_CODES.INCORRECT_PROVIDER]: {
		title: "Provider Error",
		icon: AlertTriangle,
		showRetry: false,
	},
	[AI_CODES.AUTH_ERROR]: {
		title: "Authentication Error",
		icon: Lock,
		showRetry: false,
	},
	[AI_CODES.TOO_MUCH_CONTENT]: {
		title: "Content Too Long",
		icon: AlertCircle,
		showRetry: false,
	},
	[AI_CODES.MODEL_ERROR]: {
		title: "AI Model Error",
		icon: AlertTriangle,
		showRetry: true,
	},
	[AI_CODES.UNKNOWN_ERROR]: {
		title: "Unexpected Error",
		icon: AlertCircle,
		showRetry: true,
	},
	[AI_CODES.NETWORK_ERROR]: {
		title: "Network Error",
		icon: AlertCircle,
		showRetry: true,
	},
	[AI_CODES.UNSUPPORTED_LANGUAGE]: {
		title: "Unsupported Language",
		icon: Languages,
		showRetry: false,
	},
	[AI_CODES.USER_RATE_LIMIT_EXCEEDED]: {
		title: "Rate Limit Exceeded",
		icon: Clock,
		showRetry: false,
	},
	[AI_CODES.GENERATION_STARTED]: {
		title: "Processing",
		icon: Clock,
		showRetry: false,
	},
	[AI_CODES.GLOBAL_RATE_LIMIT_EXCEEDED]: {
		title: "Service Limit Reached",
		icon: Clock,
		showRetry: false,
	},
	[AI_CODES.PROVIDER_EXHAUSTED]: {
		title: "Service Unavailable",
		icon: AlertTriangle,
		showRetry: true,
	},
};

const ERROR_MESSAGES: Record<aiErrors, string> = {
	[AI_CODES.MISSING_PARAMS]:
		"Required configuration is missing. Please check your settings.",
	[AI_CODES.UNABLE_TO_EXTRACT]:
		"This page cannot be analyzed for news content. The content may be too short or not in a readable format.",
	[AI_CODES.UNSUPPORTED_LANGUAGE]:
		"The language of this article is not supported. Currently, only English and Nepali are supported.",
	[AI_CODES.INCORRECT_PROVIDER]:
		"Invalid AI provider configured. Please update your settings.",
	[AI_CODES.AUTH_ERROR]:
		"Authentication failed. Please verify your login details, if nothing try logging out and logging back in.",
	[AI_CODES.TOO_MUCH_CONTENT]:
		"This text is longer than what our backend can process. Adding your own Gemini or Mistral API key can bypass this limit and process longer articles.",
	[AI_CODES.MODEL_ERROR]:
		"The AI model encountered an error. Please try again.",
	[AI_CODES.UNKNOWN_ERROR]:
		"An unexpected error occurred. Please try again later.",
	[AI_CODES.NETWORK_ERROR]:
		"Network error. Please check your connection and try again.",
	[AI_CODES.USER_RATE_LIMIT_EXCEEDED]:
		"You've reached your daily limit of 10 summaries. Please try again tomorrow. Consider adding your own API key to increase or remove this limit. However you can view summaries generated by others without any limits.",
	[AI_CODES.GENERATION_STARTED]:
		"Your summary is being generated. Please check back in a moment.",
	[AI_CODES.GLOBAL_RATE_LIMIT_EXCEEDED]:
		"Daily summary limit reached for all users. Please try again tomorrow. Consider adding your own API key to bypass this limit.",
	[AI_CODES.PROVIDER_EXHAUSTED]:
		"All AI providers are currently unavailable. Please try again later. Consider adding your own API key to reduce the chances of this happening in the future.",
};

export default function ErrorDisplay({
	error,
	onRetry,
	onClose,
}: ErrorDisplayProps) {
	useScreenView("/news-error", "News Error");

	const { useStateItem } = useAppState();
	const [aiSettings] = useStateItem("aiSettings");

	const setKeySettingDialogOpen = useNewsState(
		(state) => state.setKeySettingDialogOpen,
	);

	const errorCode = error || AI_CODES.UNKNOWN_ERROR;
	const config = ERROR_CONFIG[errorCode];
	const Icon = config?.icon || AlertCircle;
	const title = config?.title || "An Error Occurred";
	const showRetry = config?.showRetry ?? true;

	const keyButtonLabel = aiSettings.hasKeys ? "Edit Keys" : "Add Key";

	const shouldShowHint = ![
		AI_CODES.MISSING_PARAMS,
		AI_CODES.UNSUPPORTED_LANGUAGE,
		AI_CODES.AUTH_ERROR,
		AI_CODES.TOO_MUCH_CONTENT,
		AI_CODES.USER_RATE_LIMIT_EXCEEDED,
		AI_CODES.GLOBAL_RATE_LIMIT_EXCEEDED,
		AI_CODES.UNABLE_TO_EXTRACT,
	].includes(errorCode);

	const providerHint = aiSettings.hasKeys
		? "Double-check that your model ID and API key are valid. Most errors happen because of invalid keys, rate limits, or expired provider credentials."
		: "Many summary failures happen because the developer API keys are rate-limited or exhausted. You can add your own free API key from Gemini or Mistral, and errors usually disappear instantly.";

	return (
		<>
			<div className="space-y-3 bg-white rounded-b-xl p-2">
				<div className="flex items-center gap-2">
					<Icon className="h-5 w-5 text-red-500 shrink-0" />
					<h3 className="font-semibold text-gray-900">{title}</h3>
				</div>

				<p className="text-sm text-gray-600">{ERROR_MESSAGES[errorCode]}</p>
				{shouldShowHint && (
					<p className="text-xs text-gray-500 leading-relaxed">
						{providerHint}
					</p>
				)}
				<div className="flex gap-2">
					<Button
						onClick={() => setKeySettingDialogOpen(true)}
						variant="default"
						size="sm"
						className="text-sm flex items-center gap-1.5"
					>
						<KeyRound className="h-3.5 w-3.5" />
						{keyButtonLabel}
					</Button>

					{showRetry && onRetry && (
						<Button
							onClick={onRetry}
							variant="outline"
							size="sm"
							className="text-sm"
						>
							Try Again
						</Button>
					)}

					{onClose && (
						<Button
							onClick={onClose}
							variant="ghost"
							size="sm"
							className="text-sm"
						>
							Close
						</Button>
					)}
				</div>
			</div>

			<ApiKeySettings showIcon={false} />
		</>
	);
}
